### ISSUE TITLE
Compiler issues

### ISSUE THREAD

**Issue by LilCornDogVert** [Lynnette177/Imperial-Overwatch-aimbot#2]
Every time I try to compile and fix a line I get more problems for example Imgui.h not included so I fixed the directory but more errors pop. Don’t know what to do

**Comment by RaliVault** [comment]
change include pass and library pass.
how to change pass:
project > proparties > VC++ directions > include directions/library directions
Turn it into a place where you have what you need. (If you still don't understand this, ask ChatGPT how to change locations)

https://github.com/Lynnette177/Imperial-Overwatch-aimbot/assets/156569445/f882414f-ac5d-46ce-be30-f861123a614c

**Comment by Visusline** [comment]
> change include pass and library pass. how to change pass: project > proparties > VC++ directions > include directions/library directions Turn it into a place where you have what you need. (If you still don't understand this, ask ChatGPT how to change locations)
> 
>  VC++.links.mp4

LNK1181 cannot open interception.lib file

**Comment by RaliVault** [comment]
go to VC++,change library directions

**Comment by Visusline** [comment]
> go to VC++,change library directions
Thank you very much, do you know what causes this error?
scanning for vm...
Encrypted VM: 0x3E1E288
