### ISSUE TITLE
compiling issues with vsc

### ISSUE THREAD

**Issue by DevilishRar** [Lynnette177/Imperial-Overwatch-aimbot#4]
Error code given when running "**run build task**"
-
### _msbuild : The term 'msbuild' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparam ...
+ ~~
    + CategoryInfo          : ObjectNotFound: (msbuild:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException_
-
any help given considering that im using vsc idk what you all use to build and im very new like im very very new to building so i legit have no idea on how to build sln files or anything can i have any helped assisted?
-
**Image:** 
-
![image](https://github.com/Lynnette177/Imperial-Overwatch-aimbot/assets/164837360/db0f6a6f-980a-4cc0-8b46-68f7bde946b1)

**Comment by DevilishRar** [comment]
@Lynnette177

**Comment by Lynnette177** [comment]
Use visual studio instead.

**Comment by DevilishRar** [comment]
> Use visual studio instead.

Ok i could visual studio this purple thingy icon what should i modify and install? can you list them all theres so much like individual components and workloads @Lynnette177

**Comment by DevilishRar** [comment]
hey what file do i build i dont know what to build example.cpp? i got like 105 errors and 425 warnings just when trying to build example.cpp can you please give me some assisted help @Lynnette177 pleasee

**Comment by DevilishRar** [comment]
or maybe atleast give me alreadt built compiled imperial version
